sudo: false

language: c

os:
 - linux

compiler:
 - clang
 - gcc
 - g++

before_script:
 - ./autogen.sh

script:
 - ./configure --disable-dependency-tracking
 - >
   if [ "$TRAVIS_OS_NAME" = 'linux' -a "$CC" = 'gcc' ]; then make CFLAGS='-g0' > /dev/null && cp src/libsodium/.libs/libsodium.so lib.so && make clean > /dev/null && make CFLAGS='-g0' CPPFLAGS='-DSODIUM_C99\(X\)=' > /dev/null && cp src/libsodium/.libs/libsodium.so lib-oldc.so && cmp lib.so lib-oldc.so && echo No binary changes && make clean > /dev/null ; fi
 - make distcheck
 - make distclean > /dev/null
 - ./configure --disable-dependency-tracking --enable-minimal
 - make distcheck
 - ( echo '#include <sodium.h>' ; echo 'int main(void) { return sodium_init(); }' ) > /tmp/main.c && gcc -Isrc/libsodium/include -Isrc/libsodium/include/sodium $(find src -name '*.c' -o -name '*.S') /tmp/main.c

env:
  global:
   - secure: "P4qv8aX+nogLlSy0lTMDIR6I5OLXq+qMijB4s+oCLME5BL2xPAn3v0QG5IoHdnU0ncRc1tEYZxN3F48Rp+Q7+wEVqSBLFS3oXzfNHJGEYoiaAcPNWO0R1kF8rcy8AuoAEomNeYS+5vhzQtaXklNtx/250p6MgGuMsdpMsRUKS/U="

addons:
  coverity_scan:
    project:
      name: jedisct1/libsodium
      version: 1.0.11
      description: libsodium
      notification_email: coverityscan@pureftpd.org
      build_command_prepend: ./autogen.sh ; ./configure
      build_command: make -j4
      branch_pattern: coverity_scan
